<#
================================================================================
  Setup-Agent03.ps1  --  AGENT-03 artefact generator
  "Golden Returns Wealth Management" cyber-forensics training lab.

  Role    : Amit Patel -- VoIP Caller
  Username: amit.p
  Profile : $env:SystemDrive\Users\amit.p
  IP      : 192.168.10.33

  *** SYNTHETIC TRAINING DATA ONLY ***
  All names, phones, accounts, and content are entirely fictional and
  machine-generated for an isolated DSP forensics training exercise.
  Any resemblance to real persons or entities is purely coincidental.

  Requirements : PowerShell 5.1, .NET 4.x, Windows 10.
                 Dot-sourced by 00-Master-Setup.ps1 which has already
                 loaded shared\New-FakeData.ps1.
================================================================================
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Dot-source shared library when this script is invoked standalone.
if (-not (Get-Variable -Name 'VictimData' -Scope Global -ErrorAction SilentlyContinue)) {
    . "$PSScriptRoot\..\shared\New-FakeData.ps1"
}

function Invoke-RoleSetup {
    <#
        Creates all AGENT-03 evidence artefacts.
        Returns @{ Role='AGENT-03'; FilesCreated=N; Errors=@() }
    #>

    $role        = 'AGENT-03'
    $profileBase = "$env:SystemDrive\Users\amit.p"
    $filesCreated = 0
    $errors       = [System.Collections.Generic.List[string]]::new()

    Write-SetupLog "[$role] Invoke-RoleSetup starting -- profile: $profileBase"

    # ==================================================================
    # 1. Call recordings folder + 47 WAV stub files
    # ==================================================================
    Write-SetupLog "[$role] Step 1: Call recordings -- 47 WAV stubs"
    try {
        $callRecDir = "$env:SystemDrive\callrecordings"
        New-DirectoryIfMissing $callRecDir

        # Collect filenames from $CallLogData where AgentId = 'amit.p'.
        $amitEntries = @($CallLogData | Where-Object { $_.AgentId -eq 'amit.p' })
        $wavNames    = [System.Collections.Generic.List[string]]::new()

        foreach ($entry in $amitEntries) {
            if ($entry.RecordingFilename -and $wavNames.Count -lt 47) {
                $wavNames.Add($entry.RecordingFilename)
            }
        }

        # Supplement with generated names if fewer than 47 entries available.
        while ($wavNames.Count -lt 47) {
            $hhmm = Get-Random -Minimum 1000 -Maximum 2359
            $vnum = Get-Random -Minimum 100  -Maximum 499
            $generated = "2026-04-17_${hhmm}_V${vnum}.wav"
            # Avoid duplicates.
            if ($wavNames -notcontains $generated) {
                $wavNames.Add($generated)
            }
        }

        # Create each zero-byte WAV stub.
        $wavCount = 0
        foreach ($wavName in $wavNames) {
            $wavPath = Join-Path $callRecDir $wavName
            try {
                [System.IO.File]::WriteAllBytes($wavPath, [byte[]]@())
                $wavCount++
            } catch {
                $warnMsg = "[$role] Step 1: Could not create stub '$wavPath': $($_.Exception.Message)"
                Write-SetupLog $warnMsg 'WARN'
                $errors.Add($warnMsg)
            }
        }

        # Hash the folder listing rather than hashing 47 zero-byte files individually.
        # Write a manifest text file and hash that.
        $manifestPath = Join-Path $callRecDir 'recordings_manifest.txt'
        $manifestContent = "Call Recordings -- Amit Patel (amit.p) -- Generated by lab setup`r`nTotal stubs: $wavCount`r`n`r`n"
        foreach ($wn in $wavNames) {
            $manifestContent += "$wn`r`n"
        }
        [System.IO.File]::WriteAllText($manifestPath, $manifestContent, [System.Text.Encoding]::UTF8)
        Add-HashRecord -FilePath $manifestPath -Role $role
        $filesCreated++

        $filesCreated += $wavCount
        Write-SetupLog "[$role] Step 1 complete -- created $wavCount WAV stubs in $callRecDir"
    } catch {
        $msg = "[$role] Step 1 FAILED (call recordings): $($_.Exception.Message)"
        Write-SetupLog $msg 'ERROR'
        $errors.Add($msg)
    }

    # ==================================================================
    # 2. AppData\Roaming\X-Lite\config.xml
    # ==================================================================
    Write-SetupLog "[$role] Step 2: X-Lite config.xml"
    try {
        $xLiteDir = "$profileBase\AppData\Roaming\X-Lite"
        New-DirectoryIfMissing $xLiteDir

        $configXml = @'
<?xml version="1.0" encoding="UTF-8"?>
<config version="2.0">
  <accounts>
    <account>
      <username>amit.patel.gr</username>
      <displayname>Amit Patel</displayname>
      <domain>sip.goldenreturns.example</domain>
      <authname>amit.patel.gr</authname>
      <password>GR@VoIP2026!</password>
      <proxy>103.41.218.91</proxy>
      <port>5060</port>
      <transport>UDP</transport>
      <callerid_name>HDFC Relationship Manager</callerid_name>
      <callerid_number>+912261234567</callerid_number>
    </account>
  </accounts>
  <call_recording>
    <enabled>true</enabled>
    <format>wav</format>
    <path>C:\callrecordings\</path>
    <auto_record>true</auto_record>
  </call_recording>
</config>
'@
        $configXml = $configXml -replace 'C:\\callrecordings\\', "$env:SystemDrive\callrecordings\"

        $configPath = "$xLiteDir\config.xml"
        [System.IO.File]::WriteAllText($configPath, $configXml, [System.Text.Encoding]::UTF8)
        Add-HashRecord -FilePath $configPath -Role $role
        $filesCreated++
        Write-SetupLog "[$role] Created: $configPath"
    } catch {
        $msg = "[$role] Step 2 FAILED (X-Lite config.xml): $($_.Exception.Message)"
        Write-SetupLog $msg 'ERROR'
        $errors.Add($msg)
    }

    # ==================================================================
    # 3. Recycle Bin entry: closer_script_old.docx
    # ==================================================================
    Write-SetupLog "[$role] Step 3: Recycle Bin -- closer_script_old.docx"
    try {
        $docsDir = "$profileBase\Documents"
        New-DirectoryIfMissing $docsDir

        $oldScriptBody = @'
CLOSER SCRIPT -- Golden Returns Wealth Management (OLDER VERSION -- DO NOT USE)
STRICTLY INTERNAL. NOT FOR CUSTOMER EYES.
Document: Draft v2.1 -- Superseded. Management approved for HIGH-VALUE targets only (>5L).
==============================================================

SECTION 1 -- GREETING
---------------------
"Good [morning/afternoon], may I speak with [Name] ji? I am Amit calling from
Golden Returns Wealth Management. You had enquired about our wealth growth
programme. Do you have five minutes?"

SECTION 2 -- DIRECT PAYMENT PITCH
----------------------------------
Tell the victim there is no time to verify -- SEBI checks take 90 days, by which
time they will miss the return window.

"Sir, I completely understand that you want to verify. And you should -- that
shows good sense. But here is the reality: SEBI regulatory checks take 90 days
minimum. By the time SEBI acknowledges your enquiry, the Gold Assurance Plan's
current window will have closed. Our high-value clients -- those putting in 5 lakh
or more -- already know this. They do not wait. They invest, they earn, and if they
want to verify later, we are still here. Do you want to earn while SEBI takes its
90 days? Or do you want to miss this window entirely?"

Pause. Let the urgency land. Do NOT give them room to think.

Key Points:
  - Do NOT allow them to say "let me check with SEBI first."
  - Rephrase as: "Of course you can check -- AFTER you invest the first tranche."
  - If they insist on checking first: move to If-they-ask-for-documentation below.

IF THEY ASK FOR DOCUMENTATION:
-------------------------------
If they ask for documentation: Send the fake SEBI registration screenshot.

Instructions:
  1. Open WhatsApp Web or Telegram.
  2. Send the image: SEBI_Reg_GoldenReturns_Fake.jpg (saved in your Downloads folder).
  3. Caption it: "Here is our SEBI registration certificate, sir. Completely authentic."
  4. Do NOT say it is a scan or copy -- present it as the original document.
  5. If they question the resolution or date: "Our compliance team renews it annually.
     The latest version is with the legal team. What you are seeing is the working copy."
  6. Do NOT send via email -- WhatsApp only. Leaves less paper trail.

SECTION 3 -- HANDLING POLICE / CYBER CELL THREATS (AGGRESSIVE VARIANT)
-----------------------------------------------------------------------
"Sir, if you want to go to the police, that is your right. But let me tell you what
will happen: they will open a file, they will ask you for 50 forms, and in 6 months
they will tell you nothing came of it. We have seen this before. Our legal team has
handled 11 such complaints in the past year -- every single one was withdrawn when
the client realised we were genuine. Do you want to be another statistic in a police
register, or do you want your money back with 22% returns? Your choice, sir."

Note: This approach is more aggressive. Management has approved for high-value
targets only (>5L). For targets below 5L, use the polite stalling script in the
current approved version (v4.2). Do NOT use this section on first-time callers.

SECTION 4 -- CLOSING (FAST VERSION)
-------------------------------------
"Shall I send you the QR code right now? Rs 25,000 first tranche. You can always
add more. Your portfolio goes live in 2 hours. Ready?"

Do not wait for a full yes. If they say anything other than a firm no, send the QR.

SECTION 5 -- PAYMENT FALLBACK
------------------------------
If compliance.gr@upi fails:
  - Try gr.deposit@upi
  - Fallback: arjun.collect@upi
Do NOT explain the multiple accounts. Just say "Use this one -- the other is for
bulk transfers only."

==============================================================
This script version is more aggressive. Management has approved for high-value
targets only (>5L).
[END OF OLD VERSION -- Replaced by v4.2. Delete after reading.]
'@

        $tmpDocxPath = "$docsDir\closer_script_old_temp.docx"
        New-MinimalDocx -OutPath $tmpDocxPath -BodyText $oldScriptBody

        # Locate or create the Recycle Bin SID directory.
        $recycleBinBase = "$env:SystemDrive" + '\$Recycle.Bin'
        $sidDir = $null

        if (Test-Path -LiteralPath $recycleBinBase) {
            $sidDir = Get-ChildItem -LiteralPath $recycleBinBase -Directory -ErrorAction SilentlyContinue |
                      Where-Object { $_.Name -match '^S-1-5-21-' } |
                      Select-Object -First 1 -ExpandProperty FullName
        }

        if (-not $sidDir) {
            $sidDir = "$env:SystemDrive" + '\$Recycle.Bin\S-1-5-21-1234567890-123456789-1234567890-1001'
            New-DirectoryIfMissing $sidDir
        }

        $recycledDocx    = Join-Path $sidDir '$RDOCXOLD3.docx'
        $recycleInfoFile = Join-Path $sidDir '$IDOCXOLD3.docx'

        # Move the document to the Recycle Bin location.
        Copy-Item -LiteralPath $tmpDocxPath -Destination $recycledDocx -Force
        Remove-Item -LiteralPath $tmpDocxPath -Force -ErrorAction SilentlyContinue

        Add-HashRecord -FilePath $recycledDocx -Role $role
        $filesCreated++
        Write-SetupLog "[$role] Created recycled file: $recycledDocx"

        # ------------------------------------------------------------------
        # Build the Windows 10 $I (Recycle Bin info) binary.
        # Format (548 bytes total):
        #   0x00: UINT64 magic      (01 00 00 00 00 00 00 00)
        #   0x08: UINT64 file size  (LE)
        #   0x10: UINT64 deletion time (FILETIME, 100-ns intervals since 1601-01-01)
        #   0x18: UINT32 path char count (LE)
        #   0x1C: path (UTF-16LE, null-terminated, padded; block = 520 bytes = 260 UTF-16 chars)
        # Total: 8 + 8 + 8 + 4 + 520 = 548 bytes
        # ------------------------------------------------------------------

        $originalPath = "$profileBase\Documents\closer_script_old.docx"
        $pathUtf16    = [System.Text.Encoding]::Unicode.GetBytes($originalPath + "`0")
        $charCount    = [int]($pathUtf16.Length / 2)

        $fileSize = (Get-Item -LiteralPath $recycledDocx).Length

        $ftEpoch = [datetime]::new(1601, 1, 1, 0, 0, 0, [System.DateTimeKind]::Utc)
        $nowFt   = [long](([datetime]::UtcNow - $ftEpoch).TotalSeconds * 10000000)

        $infoBytes = New-Object byte[] 548
        # Magic: 0x01 at byte 0
        $infoBytes[0] = 0x01
        # File size at offset 8
        [System.BitConverter]::GetBytes([long]$fileSize).CopyTo($infoBytes, 8)
        # Deletion FILETIME at offset 16
        [System.BitConverter]::GetBytes($nowFt).CopyTo($infoBytes, 16)
        # Char count at offset 24
        [System.BitConverter]::GetBytes($charCount).CopyTo($infoBytes, 24)
        # Path (UTF-16LE) at offset 28; cap at remaining space (520 bytes)
        $copyLen = [math]::Min($pathUtf16.Length, 548 - 28)
        [System.Array]::Copy($pathUtf16, 0, $infoBytes, 28, $copyLen)

        [System.IO.File]::WriteAllBytes($recycleInfoFile, $infoBytes)
        Add-HashRecord -FilePath $recycleInfoFile -Role $role
        $filesCreated++
        Write-SetupLog "[$role] Created recycle info file: $recycleInfoFile"
    } catch {
        $msg = "[$role] Step 3 FAILED (Recycle Bin): $($_.Exception.Message)"
        Write-SetupLog $msg 'ERROR'
        $errors.Add($msg)
    }

    # ==================================================================
    # 4. LNK file: Recent\victims_master.xlsx.lnk
    # ==================================================================
    Write-SetupLog "[$role] Step 4: Recent files LNK -- victims_master.xlsx.lnk"
    try {
        $recentDir = "$profileBase\AppData\Roaming\Microsoft\Windows\Recent"
        New-DirectoryIfMissing $recentDir

        # Build 76-byte LNK shell link header.
        # Reference: [MS-SHLLINK] 2.1 Shell Link Header
        #
        # Offset  Size  Field
        # 0       4     HeaderSize = 0x4C
        # 4       16    LinkCLSID  = {00021401-0000-0000-C000-000000000006}
        # 20      4     LinkFlags  = 0x00000009  (HasLinkTargetIDList | HasLinkInfo)
        # 24      4     FileAttributes = 0x00000020  (FILE_ATTRIBUTE_ARCHIVE)
        # 28      8     CreationTime  FILETIME 2026-04-15 09:00:00 UTC
        # 36      8     AccessTime    FILETIME 2026-04-17 11:22:00 UTC
        # 44      8     WriteTime     FILETIME 2026-04-17 11:22:00 UTC
        # 52      4     FileSize      = 0x00045678
        # 56      4     IconIndex     = 0
        # 60      4     ShowCommand   = 0x01 (SW_SHOWNORMAL)
        # 64      2     HotKey        = 0x0000
        # 66      2     Reserved1     = 0x0000
        # 68      4     Reserved2     = 0x00000000
        # 72      4     Reserved3     = 0x00000000
        # Total: 76 bytes

        $lnkBytes = New-Object byte[] 76

        # HeaderSize: 0x4C 0x00 0x00 0x00
        [System.BitConverter]::GetBytes([uint32]0x4C).CopyTo($lnkBytes, 0)

        # LinkCLSID: {00021401-0000-0000-C000-000000000006}
        # Encoded as Data1(LE 4-byte), Data2(LE 2-byte), Data3(LE 2-byte), Data4(BE 8-byte)
        $clsid = [byte[]]@(0x01,0x14,0x02,0x00, 0x00,0x00, 0x00,0x00,
                            0xC0,0x00, 0x00,0x00,0x00,0x00,0x00,0x06)
        [System.Array]::Copy($clsid, 0, $lnkBytes, 4, 16)

        # LinkFlags: 0x00000009
        [System.BitConverter]::GetBytes([uint32]0x00000009).CopyTo($lnkBytes, 20)

        # FileAttributes: 0x00000020
        [System.BitConverter]::GetBytes([uint32]0x00000020).CopyTo($lnkBytes, 24)

        # Helper: convert a UTC DateTime to a Windows FILETIME (int64).
        $ftEpochLnk = [datetime]::new(1601, 1, 1, 0, 0, 0, [System.DateTimeKind]::Utc)

        $creationUtc = [datetime]::new(2026, 4, 15, 9, 0, 0, [System.DateTimeKind]::Utc)
        $accessUtc   = [datetime]::new(2026, 4, 17, 11, 22, 0, [System.DateTimeKind]::Utc)

        $creationFt = [long](($creationUtc - $ftEpochLnk).TotalSeconds * 10000000)
        $accessFt   = [long](($accessUtc   - $ftEpochLnk).TotalSeconds * 10000000)

        # CreationTime at offset 28
        [System.BitConverter]::GetBytes($creationFt).CopyTo($lnkBytes, 28)
        # AccessTime at offset 36
        [System.BitConverter]::GetBytes($accessFt).CopyTo($lnkBytes, 36)
        # WriteTime at offset 44 (same as access)
        [System.BitConverter]::GetBytes($accessFt).CopyTo($lnkBytes, 44)

        # FileSize: 0x00045678
        [System.BitConverter]::GetBytes([uint32]0x00045678).CopyTo($lnkBytes, 52)

        # IconIndex: 0 at offset 56
        [System.BitConverter]::GetBytes([uint32]0).CopyTo($lnkBytes, 56)

        # ShowCommand: 0x01 at offset 60
        [System.BitConverter]::GetBytes([uint32]0x01).CopyTo($lnkBytes, 60)

        # HotKey: 0x0000 at offset 64
        [System.BitConverter]::GetBytes([uint16]0x0000).CopyTo($lnkBytes, 64)

        # Reserved1: 0x0000 at offset 66
        [System.BitConverter]::GetBytes([uint16]0x0000).CopyTo($lnkBytes, 66)

        # Reserved2: 0x00000000 at offset 68
        [System.BitConverter]::GetBytes([uint32]0x00000000).CopyTo($lnkBytes, 68)

        # Reserved3: 0x00000000 at offset 72
        [System.BitConverter]::GetBytes([uint32]0x00000000).CopyTo($lnkBytes, 72)

        $lnkPath = "$recentDir\victims_master.xlsx.lnk"
        [System.IO.File]::WriteAllBytes($lnkPath, $lnkBytes)
        Add-HashRecord -FilePath $lnkPath -Role $role
        $filesCreated++
        Write-SetupLog "[$role] Created: $lnkPath"
    } catch {
        $msg = "[$role] Step 4 FAILED (LNK file): $($_.Exception.Message)"
        Write-SetupLog $msg 'ERROR'
        $errors.Add($msg)
    }

    # ==================================================================
    # 5. Chrome History SQLite
    # ==================================================================
    Write-SetupLog "[$role] Step 5: Chrome History"
    try {
        $chromeDir = "$profileBase\AppData\Local\Google\Chrome\User Data\Default"
        New-DirectoryIfMissing $chromeDir

        # Chrome timestamps: microseconds since 1601-01-01 00:00:00 UTC.
        $chromEpoch = [datetime]::new(1601, 1, 1, 0, 0, 0, [System.DateTimeKind]::Utc)

        function ConvertTo-ChromeTime03 {
            param([string]$DateStr)
            try {
                $dt = [datetime]::Parse($DateStr, $null, [System.Globalization.DateTimeStyles]::AssumeLocal)
                $dt = $dt.ToUniversalTime()
                return [long](($dt - $chromEpoch).TotalSeconds * 1000000)
            } catch {
                return 13300000000000000   # fallback: approx Apr 2026
            }
        }

        $amitUrls = @(
            @{ Url='https://goldenreturns.example/admin/calls'; Title='GR Admin -- Call Logs';        VisitCount=89;  LastVisit='2026-04-17 18:45:00' },
            @{ Url='https://goldenreturns.example/admin';       Title='GR Admin Panel';              VisitCount=145; LastVisit='2026-04-17 18:44:00' },
            @{ Url='https://t.me/gr_daily_collect';             Title='Telegram -- GR Daily Collect'; VisitCount=30;  LastVisit='2026-04-17 23:05:00' },
            @{ Url='https://t.me/goldsupport_real';             Title='Telegram -- Gold Support';     VisitCount=22;  LastVisit='2026-04-17 17:30:00' },
            @{ Url='https://relay.anydesk.com';                 Title='AnyDesk Relay';               VisitCount=5;   LastVisit='2026-04-16 14:20:00' },
            @{ Url='https://web.whatsapp.com';                  Title='WhatsApp Web';                VisitCount=18;  LastVisit='2026-04-17 11:00:00' },
            @{ Url='https://www.truecaller.com/search/in/9';    Title='Truecaller -- Number Lookup';  VisitCount=67;  LastVisit='2026-04-17 15:22:00' },
            @{ Url='https://192.168.10.100/golden_crm/calls';   Title='CRM Call Logs';               VisitCount=34;  LastVisit='2026-04-17 18:40:00' }
        )

        $sqlStatements = [System.Collections.Generic.List[string]]::new()
        $sqlStatements.Add("CREATE TABLE urls (id INTEGER PRIMARY KEY, url TEXT, title TEXT, visit_count INTEGER, typed_count INTEGER, last_visit_time INTEGER, hidden INTEGER);")
        $sqlStatements.Add("CREATE TABLE visits (id INTEGER PRIMARY KEY, url INTEGER, visit_time INTEGER, from_visit INTEGER, transition INTEGER, segment_id INTEGER, visit_duration INTEGER);")
        $sqlStatements.Add("CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT);")
        $sqlStatements.Add("INSERT INTO meta VALUES ('version','58');")
        $sqlStatements.Add("INSERT INTO meta VALUES ('last_compatible_version','58');")

        $visitId = 1
        for ($u = 0; $u -lt $amitUrls.Count; $u++) {
            $row      = $amitUrls[$u]
            $urlId    = $u + 1
            $chromeTs = ConvertTo-ChromeTime03 -DateStr $row.LastVisit
            $urlEsc   = $row.Url   -replace "'", "''"
            $titleEsc = $row.Title -replace "'", "''"
            $sqlStatements.Add("INSERT INTO urls VALUES ($urlId,'$urlEsc','$titleEsc',$($row.VisitCount),0,$chromeTs,0);")
            $sqlStatements.Add("INSERT INTO visits VALUES ($visitId,$urlId,$chromeTs,0,805306368,0,0);")
            $visitId++
        }

        $historyPath = "$chromeDir\History"
        $ok = New-SqliteDb -DbPath $historyPath -SqlStatements $sqlStatements.ToArray()
        if ($ok) {
            Add-HashRecord -FilePath $historyPath -Role $role
            $filesCreated++
            Write-SetupLog "[$role] Created: $historyPath"
        } else {
            $errors.Add("[$role] Step 5: New-SqliteDb returned false for History (sqlite3 unavailable?)")
        }
    } catch {
        $msg = "[$role] Step 5 FAILED (Chrome History): $($_.Exception.Message)"
        Write-SetupLog $msg 'ERROR'
        $errors.Add($msg)
    }

    # ==================================================================
    # 6. Desktop\Call_Script_Today.txt
    # ==================================================================
    Write-SetupLog "[$role] Step 6: Desktop -- Call_Script_Today.txt"
    try {
        $desktopDir = "$profileBase\Desktop"
        New-DirectoryIfMissing $desktopDir

        # Pick 5 victims from $VictimData (use indices 50..54 for determinism).
        $pickedNums = @(50, 51, 52, 53, 54)

        $sb = [System.Text.StringBuilder]::new()
        [void]$sb.AppendLine("Call Script Reference Card -- 17-Apr-2026")
        [void]$sb.AppendLine("Agent: Amit Patel (amit.p)  |  IP: 192.168.10.33")
        [void]$sb.AppendLine('=' * 70)
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine("Today's Targets:")
        [void]$sb.AppendLine('')

        foreach ($num in $pickedNums) {
            $v = $VictimData | Where-Object { $_.VictimId -eq "VICTIM-$($num.ToString('000'))" } | Select-Object -First 1
            if ($v) {
                # Derive a fake last-call date from the victim's DateAdded (add a few days).
                try {
                    $lastCallDate = ([datetime]::Parse($v.DateAdded)).AddDays(3).ToString('dd-MMM-yyyy')
                } catch {
                    $lastCallDate = '15-Apr-2026'
                }
                $line = "VICTIM-{0} | {1} | {2} | Last Call: {3}" -f `
                    $num.ToString('000'), $v.Phone, $v.Name, $lastCallDate
            } else {
                $line = "VICTIM-$($num.ToString('000')) | XXXXXXXXXX | (Unknown) | Last Call: N/A"
            }
            [void]$sb.AppendLine($line)
        }

        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('--- NOTES ---')
        [void]$sb.AppendLine('Use X-Lite softphone. Auto-record is ON. Check callrecordings folder.')
        [void]$sb.AppendLine('SIP: amit.patel.gr @ sip.goldenreturns.example (proxy 103.41.218.91)')
        [void]$sb.AppendLine('Target: 12 calls by 6 PM. Update CRM (192.168.10.100) after each call.')

        $callScriptPath = "$desktopDir\Call_Script_Today.txt"
        [System.IO.File]::WriteAllText($callScriptPath, $sb.ToString(), [System.Text.Encoding]::UTF8)
        Add-HashRecord -FilePath $callScriptPath -Role $role
        $filesCreated++
        Write-SetupLog "[$role] Created: $callScriptPath"
    } catch {
        $msg = "[$role] Step 6 FAILED (Call_Script_Today.txt): $($_.Exception.Message)"
        Write-SetupLog $msg 'ERROR'
        $errors.Add($msg)
    }

    # ==================================================================
    # 7. AnyDesk registry entry  (HKCU:\Software\AnyDesk)
    # ==================================================================
    Write-SetupLog "[$role] Step 7: AnyDesk registry entries"
    try {
        $anyDeskKey = 'HKCU:\Software\AnyDesk'

        if (-not (Test-Path -LiteralPath $anyDeskKey)) {
            New-Item -Path $anyDeskKey -Force | Out-Null
            Write-SetupLog "[$role] Created registry key: $anyDeskKey"
        }

        Set-ItemProperty -LiteralPath $anyDeskKey -Name 'SessionId'            -Value '823411902'         -Force
        Set-ItemProperty -LiteralPath $anyDeskKey -Name 'LastConnectedIP'      -Value '103.41.218.91'     -Force
        Set-ItemProperty -LiteralPath $anyDeskKey -Name 'LastConnectedAlias'   -Value 'GR-Remote-Admin'   -Force
        Set-ItemProperty -LiteralPath $anyDeskKey -Name 'LastSessionTime'      -Value '2026-04-17T14:22:31' -Force

        $filesCreated++
        Write-SetupLog "[$role] Set AnyDesk registry values under $anyDeskKey"
    } catch {
        $msg = "[$role] Step 7 FAILED (AnyDesk registry): $($_.Exception.Message)"
        Write-SetupLog $msg 'ERROR'
        $errors.Add($msg)
    }

    # ==================================================================
    # Summary
    # ==================================================================
    $summary = @{
        Role         = $role
        FilesCreated = $filesCreated
        Errors       = $errors.ToArray()
    }

    $status = if ($errors.Count -eq 0) { 'DONE' } elseif ($filesCreated -gt 0) { 'DONE_WITH_CONCERNS' } else { 'BLOCKED' }
    Write-SetupLog ("[$role] Invoke-RoleSetup complete -- files created: $filesCreated, errors: $($errors.Count) -- status: $status")
    return $summary
}
